** Tools

Here are some suggestions for the software tools that you may use in the course.

If you have any difficulty with the installation or usage -- then let us talk. It is better to solve this kind of problems at early stages.

*** The minimum
You will at least need Java (JDK version 8 or above) and Leiningen. You may use [[https://practicalli.github.io/clojure/development-tools/][the guide]] of Practical.li for installing them.

*** Notebooks
In most of our talks will use [[http://jupyter.org/][Jupyter]] notebooks -- not because we beleive it is the best tool, but because it is comfortable for didactic purposes.

For this course, we recommend [[https://github.com/clojupyter/lein-jupyter][lein-jupyter]], which is a convenience wrapper around [[https://github.com/clojupyter/clojupyter][clojupyter]].

**** Other options

Another way to use Jupyter is [[http://beakerx.com/][BeakerX]]. We prefer not to use it here, because it seems to play less naturally together with other tools.

Another type of notebook environment, dedicated to Clojure, is [[http://gorilla-repl.org/][gorilla-repl]], written by [[https://twitter.com/JonyEpsilon][Jony Hudson]]. It has its own visualization library and very interesting ideas regarding composable visual reports. It is rather common among Clojure data scientists. Another version of it is [[https://github.com/deas/gorilla-notebook][gorilla-notebook]].

*** Editors
At about the 4th meeting, when we start writing larger pieces of code, it will become important to use a proper code editor.

Practical.li has nice [[https://practicalli.github.io/clojure/development-tools/install-guides/][installation guides]] for several editors.

At our talks we will use VSCode.

**** Other options

If you like Emacs, then you can also use the [[https://www.braveclojure.com/basic-emacs/][installation guide]] at Higginbotham's book.

If you like Spacemacs, then you can also use the more [[https://practicalli.github.io/spacemacs/][detailed guide]] by Practical.li.

Another option is [[https://sekao.net/nightcode/][Nightcode]] - a minimalistic editor, dedicated to Clojure, which is rather easy to install.

*** Trying Clojure online.

 For your practice, you may also use Clojure online.
 - [[https://repl.it/languages/clojure][repl.it]] - here you can try the language online.

